version: "3.8"
services:
  mongodb:
    image : mongo
    hostname: mongodb
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./database:/data/db
    ports:
    - 27017:27017
    expose:
    - 27017
    restart: unless-stopped
  steamapi:
    image: steamapi
    container_name: steamapi
    environment:
    - MONGODB_HOST=mongodb
    - MONGODB_PORT=27017
    depends_on:
      - mongodb
    ports:
    - 9100:9100
    #expose:
    #- 9100
    restart: unless-stopped
  steamscraper:
    image: scraper_api
    container_name: scraper_api
    environment:
    - STEAM_MONGODB_HOST=mongodb
    - STEAM_MONGODB_PORT=27017
    - FLASK_APP=ScraperAPI.py
    - FLASK_ENV=development # change when deployed to prod
    depends_on:
      - mongodb
    ports: 
      - 9080:9080